### ISSUE TITLE
Epic: research poc

### ISSUE THREAD

**Issue by arsenyjin** [Curve-Labs/primeDAO#2]
In order to proceed with the further development we should build a [PoC of a DAO powered by daostack](https://daostack.github.io/DAOstack-Hackers-Kit/gettingStarted/setupGenericScheme/) with the [curve bonding based reputation minting](https://github.com/Curve-Labs/openraise-dapp)

Definition of done:
- [ ] DAO deployed on a local testnet
- [ ] bonding curve scheme with minting function
- [ ] simple tests pass
- [ ] PoC quality

After the `PoC phase` is complete we can proceed to the `phase 0`
